spring.application.name=employee-management-system

spring.datasource.url = jdbc:mysql://localhost:3307/employee_department_system
spring.datasource.username = root
spring.datasource.password = Mysql


server.servlet.context-path=/employee-management-system

## Spring MVC View Configuration (JSP)
spring.mvc.view.prefix=/WEB-INF/jsps/
spring.mvc.view.suffix=.jsp


## Spring Security Configuration (if needed)
#spring.security.user.name=pratik
#spring.security.user.password=123


### QUERIES ###
FETCH_USER=select * from users where id = ?

FETCH_USERS=select * from users;

FETCH_DEPARTMENTS=select * from departments;

PERSIST_USER=insert into users (first_name, last_name, email, password, contact_num) values(?, ?, ?, ?, ?);

FIND_BY_EMAILID=select * from users where email = 

FETCH_PENDING_USERS=select edr.id, edr.emp_id, u.first_name, u.last_name, u.email, edr.depart_id, d.department, u.status from emp_depart_requests edr join users u on u.id = edr.emp_id join departments d on d.id = edr.depart_id order by id asc;

#ROLE_REQUEST=update users set status = ?, role = ? where id = ?;
ROLE_REQUEST=update users set status = ? where id = ?;

ROLE_ASSIGN=insert into emp_depart (emp_id, depart_id) values (?, ?);

FETCH_STATUS=select status from users where id = ?; 

#SUPPORT_LOGIN=select emp_id, depart_id from emp_depart where emp_id = ? and depart_id = ? 
#EMPLOYEE_LOGIN=select ed.emp_id, ed.depart_id, u.email, d.department from emp_depart ed join users u on u.id = ed.emp_id join departments d on ed.depart_id = d.id WHERE u.id = ?
EMPLOYEE_LOGIN=select d.depart_code FROM emp_depart ed JOIN departments d ON ed.depart_id = d.id where ed.emp_id = ?;

#FETCH_ROLE=select department from departments d join emp_depart ed on ed.depart_id = d.id join users u on u.id = ed.emp_id where u.id = ?;
#FETCH_DEPART_ID=select depart_id from emp_depart where emp_id = ?

GET_REQUEST_FOR_ROLE=select depart_code from departments where depart_code = ?;

CHANGE_STATUS_TO_PENDING=update users set status = 'PENDING' where id = ?;

CHANGE_STATUS_TO_APPROVED=update users set status = 'APPROVED' where id = ?;
#CHANGE_STATUS=UPDATE users SET status = 'PENDING' WHERE id = ? AND EXISTS (SELECT 1 FROM departments WHERE depart_code = ?);

#FETCH_LINKED_DEPARTMENT=select d.department from departments d join emp_depart ed on d.id = ed.depart_id join users u on ed.emp_id = u.id where u.id = ?;
FETCH_LINKED_DEPARTMENT=select d.department from departments d join emp_depart ed on d.id = ed.depart_id join users u on ed.emp_id = u.id where ed.emp_id = ?;

FETCH_LANDING_PAGE=select d.landing_page, d.allowed_view from departments d join emp_depart ed on d.id = ed.depart_id join users u on ed.emp_id = u.id where u.id = ?;

EMPLOYEES_LIST_FOR_HR=select distinct u.* from users u join emp_depart ed on u.id = ed.emp_id join departments d on d.id = ed.depart_id where u.`status` = 'APPROVED' AND (d.depart_code = "SPRT_02" or d.depart_code = "HR_03" or d.depart_code = "IT_04" or d.depart_code = "FIN_05");

DEPARTMENT_REQUEST=insert into emp_depart_requests (emp_id, depart_id) values (?, ?);

DEPARTMENT_REQUEST_APPROVE=insert into emp_depart (emp_id, depart_id) values (?, ?);

DELETE_ENTRY_FOR_DEPARTMENT_REQUEST=delete from emp_depart_requests where emp_id = ? and depart_id = ?;

SAVE_UPDATED_EMPLOYEE=update users set first_name = ?, last_name = ?, email = ?, contact_num = ? where id = ?;